--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kios/Pictures/Wallpapers/kaworu.jpg"

-- Special
background="#060505"
foreground="#e6ccc4"
cursor="#e6ccc4"

-- Colors
color0="#060505"
color1="#C67061"
color2="#AE8676"
color3="#D1896D"
color4="#7B8B81"
color5="#B09B91"
color6="#CD9889"
color7="#e6ccc4"
color8="#a18e89"
color9="#C67061"
color10="#AE8676"
color11="#D1896D"
color12="#7B8B81"
color13="#B09B91"
color14="#CD9889"
color15="#e6ccc4"
