# Shell variables
# Generated by 'wal'
wallpaper='/home/kios/Pictures/Wallpapers/kaworu.jpg'

# Special
background='#060505'
foreground='#e6ccc4'
cursor='#e6ccc4'

# Colors
color0='#060505'
color1='#C67061'
color2='#AE8676'
color3='#D1896D'
color4='#7B8B81'
color5='#B09B91'
color6='#CD9889'
color7='#e6ccc4'
color8='#a18e89'
color9='#C67061'
color10='#AE8676'
color11='#D1896D'
color12='#7B8B81'
color13='#B09B91'
color14='#CD9889'
color15='#e6ccc4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
